--1--
SELECT  STUDENT_NAME,STUDENT_ADDRESS
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2--
SELECT  STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN='Y'
ORDER BY STUDENT_SSN DESC;

--3--
SELECT  STUDENT_NAME AS "학생이름",
        STUDENT_NO AS "학번", 
        STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' 
        OR STUDENT_ADDRESS LIKE '강원도%')
        AND TO_CHAR(STUDENT_NO) LIKE '9%'
ORDER BY STUDENT_NAME;

--4--
SELECT A.PROFESSOR_NAME, A.PROFESSOR_SSN
FROM TB_PROFESSOR A
JOIN TB_DEPARTMENT B
ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
WHERE B.DEPARTMENT_NAME = '법학과'
ORDER BY A.PROFESSOR_SSN;

--5--
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM90.00') AS POINT
FROM TB_GRADE
WHERE TERM_NO = 200402 AND CLASS_NO='C3118100'
ORDER BY POINT DESC;

--6--
SELECT A.STUDENT_NO, A.STUDENT_NAME, B.DEPARTMENT_NAME
FROM TB_STUDENT A
JOIN TB_DEPARTMENT B
ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
ORDER BY A.STUDENT_NAME;

--7--
SELECT A.CLASS_NAME, B.DEPARTMENT_NAME
FROM TB_CLASS A
JOIN TB_DEPARTMENT B
ON A.DEPARTMENT_NO = B.DEPARTMENT_NO
ORDER BY B.DEPARTMENT_NAME, A.CLASS_NAME;

--8--
SELECT B.CLASS_NAME  , C.PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR A
    JOIN TB_CLASS B  ON A.CLASS_NO = B.CLASS_NO
    JOIN TB_PROFESSOR C ON A.PROFESSOR_NO = C.PROFESSOR_NO
ORDER BY B.CLASS_NAME,C.PROFESSOR_NAME;
    
--9--
SELECT B.CLASS_NAME  , C.PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR A
    JOIN TB_CLASS B  ON A.CLASS_NO = B.CLASS_NO
    JOIN (
        SELECT CA.PROFESSOR_NO AS PROFESSOR_NO, 
                CA.PROFESSOR_NAME AS PROFESSOR_NAME,
                CB.CATEGORY AS CATEGORY
        FROM TB_PROFESSOR CA
        JOIN TB_DEPARTMENT CB
        ON CA.DEPARTMENT_NO = CB.DEPARTMENT_NO
    )C ON A.PROFESSOR_NO = C.PROFESSOR_NO
WHERE C.CATEGORY = '인문사회'
ORDER BY B.CLASS_NAME, C.PROFESSOR_NAME;

--10--
SELECT A.STUDENT_NO AS "학번", 
        (
            SELECT SUBA.STUDENT_NAME
            FROM TB_STUDENT SUBA
            WHERE A.STUDENT_NO = SUBA.STUDENT_NO
        ) AS  "학생 이름",
        ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_STUDENT A
    JOIN TB_GRADE B ON A.STUDENT_NO = B.STUDENT_NO
    JOIN TB_DEPARTMENT C ON A.DEPARTMENT_NO =C.DEPARTMENT_NO
WHERE C.DEPARTMENT_NAME ='음악학과'
GROUP BY A.STUDENT_NO
ORDER BY A.STUDENT_NO;

--11--
SELECT C.DEPARTMENT_NAME AS "학과이름",
        A.STUDENT_NAME AS "학생이름",
        B.PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT A
    JOIN TB_PROFESSOR B ON A.COACH_PROFESSOR_NO = B.PROFESSOR_NO
    JOIN TB_DEPARTMENT C ON A.DEPARTMENT_NO = C.DEPARTMENT_NO
WHERE A.STUDENT_NO ='A313047';

--12--
SELECT C.STUDENT_NAME ,
        A.TERM_NO AS "TERM_NAME" 
FROM TB_GRADE A
    JOIN TB_CLASS B ON A.CLASS_NO = B.CLASS_NO
    JOIN TB_STUDENT C ON A.STUDENT_NO = C.STUDENT_NO
WHERE B.CLASS_NAME = '인간관계론' AND SUBSTR(A.TERM_NO, 1,4)='2007'
ORDER BY C.STUDENT_NAME;

--13--
SELECT A.CLASS_NAME , 
        D.DEPARTMENT_NAME 
FROM TB_CLASS A
    LEFT JOIN TB_CLASS_PROFESSOR B ON A.CLASS_NO = B.CLASS_NO
    LEFT JOIN TB_PROFESSOR C ON B.PROFESSOR_NO = C.PROFESSOR_NO
    LEFT JOIN TB_DEPARTMENT D ON A.DEPARTMENT_NO = D.DEPARTMENT_NO
WHERE D.CATEGORY ='예체능' AND B.PROFESSOR_NO IS NULL
ORDER BY D.DEPARTMENT_NAME, A.CLASS_NAME
