
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE CUSTOMERS;
DROP SEQUENCE ORDERSEQ;
DROP SEQUENCE PRODUCTSEQ;
DROP SEQUENCE CUSTOMERSEQ;

--1--

CREATE SEQUENCE ORDERSEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCTSEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE CUSTOMERSEQ START WITH 101 INCREMENT BY 1;

CREATE TABLE CUSTOMERS(
    CNO NUMBER(5) PRIMARY KEY,
    CNAME VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL
);

CREATE TABLE PRODUCTS(
    PNO NUMBER(5) PRIMARY KEY,
    PNAME VARCHAR2(20) NOT NULL,
    COST NUMBER(8) DEFAULT 0 NOT NULL ,
    STOCK NUMBER(5) DEFAULT 0 NOT NULL
);

CREATE TABLE ORDERS(
    ORDERNO NUMBER(10) PRIMARY KEY,
    ORDERDATE DATE DEFAULT SYSDATE NOT NULL,
    ADDRESS VARCHAR2(50) NOT NULL ,
    PHONE VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL ,
    CNO NUMBER(5) NOT NULL REFERENCES CUSTOMERS(CNO) ,
    CHECK(STATUS IN ('°áÁ¦¿Ï·á','¹è¼ÛÁß','¹è¼Û¿Ï·á'))
);

CREATE TABLE ORDERDETAIL(
    ORDERNO NUMBER(10) REFERENCES ORDERS(ORDERNO),
    PNO NUMBER(5) REFERENCES PRODUCTS(PNO),
    QTY NUMBER(5) DEFAULT 0 ,
    COST NUMBER(8) DEFAULT 0,
    PRIMARY KEY(ORDERNO, PNO)
);

--2--
INSERT INTO PRODUCTS VALUES(PRODUCTSEQ.NEXTVAL,'»ï¾ç¶ó¸é',1000,200);
INSERT INTO PRODUCTS VALUES(PRODUCTSEQ.NEXTVAL,'»õ¿ì±ø',1500,500);
INSERT INTO PRODUCTS VALUES(PRODUCTSEQ.NEXTVAL,'¿ùµåÄÜ',2000,350);
INSERT INTO PRODUCTS VALUES(PRODUCTSEQ.NEXTVAL,'»©»©·Î',2000,700);
INSERT INTO PRODUCTS VALUES(PRODUCTSEQ.NEXTVAL,'ÄÚÄ«ÄÝ¶ó',1800,550);
INSERT INTO PRODUCTS VALUES(PRODUCTSEQ.NEXTVAL,'È¯Å¸',1600,300);
SELECT * FROM PRODUCTS;

--3--
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL,'±èÃ¶¼ö','¼­¿ï °­³²±¸', 'cskim@naver.com','899-6666');
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL,'ÀÌ¿µÈñ','ºÎ»ê ¼­¸é', 'yhlee@empal.com','355-8882');
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL,'ÃÖÁø±¹','Á¦ÁÖ µ¿±¤¾ç', 'jkchoi@gmail.com','852-5764');
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL,'°­ÁØÈ£','°­¸ª È«Á¦µ¿', 'jhkang@hanmail.com','559-7777');
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL,'¹Îº´±¹','´ëÀü Àü¹Îµ¿', 'bgmin@hotmail.com','559-8741');
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL,'¿À¹Î¼ö','±¤ÁÖ ºÏ±¸', 'msoh@microsoft.com','542-9988');
SELECT * FROM CUSTOMERS;

--4--
INSERT INTO ORDERS (ORDERNO, ORDERDATE, ADDRESS, PHONE, STATUS, CNO)
VALUES(
    ORDERSEQ.NEXTVAL,
    SYSDATE-3,
    '¼­¿ï °­³²±¸',
    '899-6666',
    '°áÁ¦¿Ï·á',
    (SELECT CNO FROM CUSTOMERS WHERE CNAME='±èÃ¶¼ö')
);
SELECT * FROM ORDERS;

INSERT INTO ORDERDETAIL (ORDERNO,PNO, QTY, COST)
VALUES(
    (
        SELECT ORDERNO
        FROM ORDERS
        WHERE CNO = (SELECT CNO FROM CUSTOMERS WHERE CNAME='±èÃ¶¼ö')
    ),
    (SELECT PNO 
        FROM PRODUCTS
        WHERE PNAME = '»ï¾ç¶ó¸é'
    ),
    50,
    1000
);
SELECT * FROM ORDERDETAIL;

--5--
UPDATE PRODUCTS
SET STOCK = STOCK - (
        SELECT QTY
        FROM ORDERDETAIL 
        WHERE ORDERNO=1
    )
WHERE PNO = (
            SELECT PNO
            FROM ORDERDETAIL
            WHERE ORDERNO =1
        );
SELECT * FROM PRODUCTS;

--6--
INSERT INTO ORDERS (ORDERNO, ORDERDATE, ADDRESS, PHONE, STATUS, CNO)
VALUES(
    ORDERSEQ.NEXTVAL,
    SYSDATE-2,
    'ºÎ»ê ¼ö¿µ±¸',
    '337-5000',
    '°áÁ¦¿Ï·á',
    (SELECT CNO FROM CUSTOMERS WHERE CNAME='ÀÌ¿µÈñ')
);
SELECT * FROM ORDERS;

INSERT INTO ORDERDETAIL (ORDERNO,PNO, QTY, COST)
VALUES(
    (
        SELECT ORDERNO
        FROM ORDERS
        WHERE CNO = (SELECT CNO FROM CUSTOMERS WHERE CNAME='ÀÌ¿µÈñ')
    ),
    (SELECT PNO 
        FROM PRODUCTS
        WHERE PNAME = '»õ¿ì±ø'
    ),
    100,
    1500
);
INSERT INTO ORDERDETAIL (ORDERNO,PNO, QTY, COST)
VALUES(
    (
        SELECT ORDERNO
        FROM ORDERS
        WHERE CNO = (SELECT CNO FROM CUSTOMERS WHERE CNAME='ÀÌ¿µÈñ')
    ),
    (SELECT PNO 
        FROM PRODUCTS
        WHERE PNAME = '¿ùµåÄÜ'
    ),
    150,
    2000
);
SELECT * FROM ORDERDETAIL;

--7--
UPDATE PRODUCTS
SET STOCK = STOCK - (
                        SELECT QTY 
                        FROM ORDERDETAIL 
                        WHERE ORDERNO =2 
                            AND PNO =(SELECT PNO 
                                            FROM PRODUCTS
                                            WHERE PNAME = '»õ¿ì±ø'
                                        )
                        )
WHERE PNAME = '»õ¿ì±ø';

UPDATE PRODUCTS
SET STOCK = STOCK - (
                        SELECT QTY 
                        FROM ORDERDETAIL 
                        WHERE ORDERNO =2 
                            AND PNO =(SELECT PNO 
                                            FROM PRODUCTS
                                            WHERE PNAME = '¿ùµåÄÜ'
                                        )
                        )
WHERE PNAME = '¿ùµåÄÜ';

SELECT * FROM PRODUCTS;

--8--
INSERT INTO ORDERS (ORDERNO, ORDERDATE, ADDRESS, PHONE, STATUS, CNO)
VALUES(
    ORDERSEQ.NEXTVAL,
    SYSDATE-1,
    '±¤ÁÖ ºÏ±¸',
    '652-2277',
    '°áÁ¦¿Ï·á',
    (SELECT CNO FROM CUSTOMERS WHERE CNAME='¿À¹Î¼ö')
);
SELECT * FROM ORDERS;

INSERT INTO ORDERDETAIL (ORDERNO,PNO, QTY, COST)
VALUES(
    (
        SELECT ORDERNO
        FROM ORDERS
        WHERE CNO = (SELECT CNO FROM CUSTOMERS WHERE CNAME='¿À¹Î¼ö')
    ),
    (SELECT PNO 
        FROM PRODUCTS
        WHERE PNAME = '»©»©·Î'
    ),
    100,
    2000
);
INSERT INTO ORDERDETAIL (ORDERNO,PNO, QTY, COST)
VALUES(
    (
        SELECT ORDERNO
        FROM ORDERS
        WHERE CNO = (SELECT CNO FROM CUSTOMERS WHERE CNAME='¿À¹Î¼ö')
    ),
    (SELECT PNO 
        FROM PRODUCTS
        WHERE PNAME = 'ÄÚÄ«ÄÝ¶ó'
    ),
    50,
    1800
);
SELECT * FROM ORDERDETAIL;

--9--
UPDATE PRODUCTS
SET STOCK = STOCK - (
                        SELECT QTY 
                        FROM ORDERDETAIL 
                        WHERE ORDERNO =3
                            AND PNO =(SELECT PNO 
                                            FROM PRODUCTS
                                            WHERE PNAME = '»©»©·Î'
                                        )
                        )
WHERE PNAME = '»©»©·Î';

UPDATE PRODUCTS
SET STOCK = STOCK - (
                        SELECT QTY 
                        FROM ORDERDETAIL 
                        WHERE ORDERNO =3
                            AND PNO =(SELECT PNO 
                                            FROM PRODUCTS
                                            WHERE PNAME = 'ÄÚÄ«ÄÝ¶ó'
                                        )
                        )
WHERE PNAME = 'ÄÚÄ«ÄÝ¶ó';

SELECT * FROM PRODUCTS;

--10--
SELECT B.ORDERDATE, C.CNAME, B.ADDRESS, B.PHONE, B.STATUS, D.PNAME, A.COST, A.QTY, A.COST*A.QTY
FROM ORDERDETAIL A
    JOIN ORDERS B ON A.ORDERNO =B.ORDERNO
    JOIN CUSTOMERS C ON B.CNO = C.CNO
    JOIN PRODUCTS D ON A.PNO = D.PNO;
    
--11--
SELECT ORDERDATE, SUM(COST*QTY)
FROM ORDERDETAIL 
    JOIN ORDERS USING(ORDERNO)
GROUP BY ORDERDATE;

--12--
INSERT INTO PRODUCTS VALUES(1007,'¸ñÄµµð',3000,500);
SELECT * FROM PRODUCTS;

--13--
INSERT INTO ORDERS (ORDERNO, ORDERDATE, ADDRESS, PHONE, STATUS, CNO)
VALUES(
    ORDERSEQ.NEXTVAL,
    SYSDATE,
    'Á¦ÁÖ µ¿±¤¾ç',
    '352-4657',
    '°áÁ¦¿Ï·á',
    (SELECT CNO FROM CUSTOMERS WHERE CNAME='ÃÖÁø±¹')
);
SELECT * FROM ORDERS;

INSERT INTO ORDERDETAIL (ORDERNO,PNO, QTY, COST)
VALUES(
    (
        SELECT ORDERNO
        FROM ORDERS
        WHERE CNO = (SELECT CNO FROM CUSTOMERS WHERE CNAME='ÃÖÁø±¹')
    ),
    (SELECT PNO 
        FROM PRODUCTS
        WHERE PNAME = '¸ñÄµµð'
    ),
    200,
    3000
);
SELECT * FROM ORDERDETAIL;
SELECT B.ORDERDATE, C.CNAME, B.ADDRESS, B.PHONE, B.STATUS, D.PNAME, A.COST, A.QTY, A.COST*A.QTY
FROM ORDERDETAIL A
    JOIN ORDERS B ON A.ORDERNO =B.ORDERNO
    JOIN CUSTOMERS C ON B.CNO = C.CNO
    JOIN PRODUCTS D ON A.PNO = D.PNO;